[meta]
name     = "Item Placement Toolbox"
author   = "XertroV"
category = "Map Editor"
version  = "0.4.9"
siteid   = 340

[script]
#__DEFINES__
dependencies = ["Camera"]
# optional_dependencies = ["MLHook"]
